name: pipeline
on:
  push:
    branches:
      - "go_app_compose_cdci"

jobs:
  deploy:
    name: build && push image to Docker Hub
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          ref: go_app_compose_cdci

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push api
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          push: true
          tags: linhbngo/go_server:latest
